#
# Makefile for 8bit-LED Device Driver
# Hanback Electronics Co.,ltd
# Date : September 30,2009
#

CC     = arm-linux-gcc

obj-m := ledioport.o

KDIR:=/Android/linux-2.6.29.0-hanback

PWD:= $(shell pwd)

TEST_TARGET = led_test
TEST_SRCS = $(TEST_TARGET).c

default:$(TEST_TARGET)
	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
	$(CC) $(TEST_SRCS) -static -o $(TEST_TARGET)
	rm -f default

clean:
	rm -f *.ko
	rm -f *.o
	rm -f *.mod.*
	rm -f .*.cmd
	rm -f $(TEST_TARGET)
